openapi: 3.0.0
info:
  title: ESMSCC API
  version: 1.0.0

servers:
  - url: http://localhost/api
    description: Lokale Entwicklungsumgebung

paths:
  /example:
    get:
      summary: "example endpoint"
      responses:
        '200':
          description: "Hello World"
